language: python
python:
  - 2.7
services:
  - elasticsearch
  - redis
before_install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  - echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
  - sudo apt-get update -qq
  - sudo apt-get install -y mongodb-org=2.6.7
  - sudo /usr/share/elasticsearch/bin/plugin install elasticsearch/elasticsearch-analysis-icu/2.4.1
  - sudo service elasticsearch restart
  - mongo --version
install:
  - travis_retry pip install -r travis.$TRAVIS_BRANCH.pip
  - pip install -e .
script:
  - nosetests udata_gouvfr
branches:
  only:
    - master
    - dev
