language: python
python:
  - 2.7
services:
  - mongodb
before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgeos-dev libgdal-dev
  - sudo /usr/share/elasticsearch/bin/plugin -install elasticsearch/elasticsearch-analysis-icu/2.3.0
  - sudo service elasticsearch start
install:
  - pip install -r travis.pip --allow-external webassets --allow-unverified webassets
  - pip install --no-deps -e .
script:
  - nosetests --with-coverage udata_gouvfr
after_success:
  - coveralls --rcfile=coverage.rc
